apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: peterheybrock/capstone:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8081
